### ISSUE TITLE
Keyboard input issues

### ISSUE THREAD

**Issue by dlech** [G33kDude/ev3dev-web-remote#2]
- [ ] One thing I mentioned on irc already is that there is a POST request every time you press a key, which is probably not the most efficient.
- [ ] Every time you press a key, it creates a new uinput device. This fills up the systemd journal with entries like this:
  
  ```
  Oct 16 02:18:03 ev3dev kernel: input: py-evdev-uinput as /devices/virtual/input/input656
  ```
  
  Apparently I have pressed a key 655 times. Also, this confuses ev3devKit because the device disappears so quickly. This leads to errors in the brickman log since it uses ev3devKit.
- [ ] When I tried to use the keyboard shortcut of `CTRL` + `+`, there was an unhandled exception, presumably because of the `CTRL` key. It would be nice if `CTRL` and `ALT` keystrokes were still handled by the browser.

**Comment by dlech** [comment]
The uinput issue is fixed.

Still would be nice to not eat CTRL key presses.

**Comment by dlech** [comment]
Example of unhanded exception when typing `CTRL + W` or something like that.

```
written 324
192.168.0.113 - - [01/Jan/2016 02:44:06] "POST /send.key HTTP/1.1" 200 -
written 325
 ----------------------------------------
Exception happened during processing of request from ('192.168.0.113', 41387)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
192.168.0.113 - - [01/Jan/2016 02:44:06] "POST /send.key HTTP/1.1" 200 -
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
----------------------------------------
Exception happened during processing of request from ('192.168.0.113', 41388)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./server.py", line 63, in do_POST
    KEYBOARD.send_key(int(jskc), int(state))
  File "/home/robot/ev3dev-web-remote/keyboard.py", line 109, in send_key
    self.handle_one_request()
    self.uinput.write(evdev.ecodes.EV_KEY, js_map[js_keycode], 1 if state else 0)
KeyError: 61
----------------------------------------
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./server.py", line 63, in do_POST
    KEYBOARD.send_key(int(jskc), int(state))
  File "/home/robot/ev3dev-web-remote/keyboard.py", line 109, in send_key
    self.uinput.write(evdev.ecodes.EV_KEY, js_map[js_keycode], 1 if state else 0)
KeyError: 61
----------------------------------------
written 326
192.168.0.113 - - [01/Jan/2016 02:44:06] "POST /send.key HTTP/1.1" 200 -
written 327
```
